CREATE TABLE dinosaurs (id INT AUTO_INCREMENT NOT NULL, enclosure_id INT DEFAULT NULL, length INT NOT NULL, genus VARCHAR(255) NOT NULL, is_carnivorous TINYINT(1) NOT NULL, INDEX IDX_B1DE6E91D04FE1E5 (enclosure_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE securities (id INT AUTO_INCREMENT NOT NULL, enclosure_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_A8210B24D04FE1E5 (enclosure_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE enclosures (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE dinosaurs ADD CONSTRAINT FK_B1DE6E91D04FE1E5 FOREIGN KEY (enclosure_id) REFERENCES enclosures (id);
ALTER TABLE securities ADD CONSTRAINT FK_A8210B24D04FE1E5 FOREIGN KEY (enclosure_id) REFERENCES enclosures (id);
